baseurl = "/"
title = "Stromberg Labs"
sidebar = "Projects!"
theme = "hugo-creative-portfolio-theme"
languageCode = "en-us"

[params]
  # Style options: default (pink), blue, green, pink, red, sea, violet
  # Use custom.css for your custom styling
  style = "green"
  description = "A little website to host my projects"

  # Nav links in the side bar
  [[params.navlinks]]
  name = "Home"
  url = ""

  [[params.navlinks]]
  name = "About"
  url = "about/"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
